// Generated by Biss.Apps.Generator - 02.02.2022 06:41:30
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// ReSharper disable once CheckNamespace
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewEditGatewayQ
	{
		public ViewEditGatewayQ() : this(null)
		{
		}

		public ViewEditGatewayQ(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
