// Generated by Biss.Apps.Generator - 28.01.2022 13:45:37
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// ReSharper disable once CheckNamespace
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewEditMeasurementDefinition
	{
		public ViewEditMeasurementDefinition() : this(null)
		{
		}

		public ViewEditMeasurementDefinition(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
