// Generated by Biss.Apps.Generator - 04.02.2022 15:14:56

using System;
using BDA.Common.Exchange.Enum;
using Exchange.Enum;
using Exchange.Extensions;
using Exchange.Resources;
using Xamarin.Forms;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// ReSharper disable once CheckNamespace
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewEditIotDevice
	{
		public ViewEditIotDevice() : this(null)
		{
		}

		public ViewEditIotDevice(object? args = null) : base(args)
		{
			InitializeComponent();
		}

        private void InputView_OnTextChanged(object sender, TextChangedEventArgs e)
        {
            ViewModel.UpdateAdditionalConfig();
        }

        private void Editor_OnCompleted(object sender, EventArgs e)
        {
            ViewModel.UpdateAdditionalConfig();
        }

        #region Headers

        public string DotnetHeader => EnumIotDevicePlattforms.DotNet.GetDisplayName();
        public string RaspberryHeader => EnumIotDevicePlattforms.RaspberryPi.GetDisplayName();
        public string EspHeader => EnumIotDevicePlattforms.Esp32.GetDisplayName();
        public string PrebuiltHeader => EnumIotDevicePlattforms.Prebuilt.GetDisplayName();

        #endregion

        #region Plattforminfos

        public string PlattformText1 => string.Format(ResViewEditIotDevice.Txt_PlattformModal1, ResEnumTranslations.EnumIotDeviceUpstreamTypes_Tcp);

        public string PlattformText2 => string.Format(ResViewEditIotDevice.Txt_PlattformModal2, ResEnumTranslations.EnumIotDeviceUpstreamTypes_Tcp);

        public string PlattformText3 => string.Format(ResViewEditIotDevice.Txt_PlattformModal3, ViewModel?.EntryOpensenseBoxId?.Title ?? string.Empty);

        public string PlattformText4 => string.Format(ResViewEditIotDevice.Txt_PlattformModal4);

        public string PlattformText5 => string.Format(ResViewEditIotDevice.Txt_PlattformModal5);

        #endregion




    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
