// Generated by Biss.Apps.Generator - 26.01.2022 07:14:13
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// ReSharper disable once CheckNamespace
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewInfrastructure
	{
		public ViewInfrastructure() : this(null)
		{
		}

		public ViewInfrastructure(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
