// Generated by Biss.Apps.Generator - 26.01.2022 07:14:13

using System.Diagnostics;
using Xamarin.Forms;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// ReSharper disable once CheckNamespace
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewInfrastructureQ
	{
		public ViewInfrastructureQ() : this(null)
		{
		}

		public ViewInfrastructureQ(object? args = null) : base(args)
		{
			InitializeComponent();
		}

    }
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
