// Generated by Biss.Apps.Generator - 06.02.2022 18:58:43
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// ReSharper disable once CheckNamespace
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewConfigs
	{
		public ViewConfigs() : this(null)
		{
		}

		public ViewConfigs(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
