// Generated by Biss.Apps.Generator - 09.02.2022 10:13:57
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// ReSharper disable once CheckNamespace
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewAddGatewayToCompanyQ
	{
		public ViewAddGatewayToCompanyQ() : this(null)
		{
		}

		public ViewAddGatewayToCompanyQ(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
