// Generated by Biss.Apps.Generator - 17.01.2022 14:24:32
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewMain
	{
		public ViewMain() : this(null)
		{
		}

		public ViewMain(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
