// Generated by Biss.Apps.Generator - 21.10.2021 09:37:07
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewMapFilter
	{
		public ViewMapFilter() : this(null)
		{
		}

		public ViewMapFilter(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
