// Generated by Biss.Apps.Generator - 26.01.2022 09:40:32
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// ReSharper disable once CheckNamespace
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewCompany
	{
		public ViewCompany() : this(null)
		{
		}

		public ViewCompany(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
