// Generated by Biss.Apps.Generator - 18.01.2022 12:06:35
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewAddUser
	{
		public ViewAddUser() : this(null)
		{
		}

		public ViewAddUser(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
