// Generated by Biss.Apps.Generator - 07.02.2022 13:52:51
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// ReSharper disable once CheckNamespace
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewEditGlobalConfig
	{
		public ViewEditGlobalConfig() : this(null)
		{
		}

		public ViewEditGlobalConfig(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
