// Generated by Biss.Apps.Generator - 19.01.2022 08:21:53
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// ReSharper disable once CheckNamespace
namespace BaseApp.View.Xamarin.View
{
	public partial class ViewAddProjectQ
	{
		public ViewAddProjectQ() : this(null)
		{
		}

		public ViewAddProjectQ(object? args = null) : base(args)
		{
			InitializeComponent();
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
