//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResEnumTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResEnumTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResEnumTranslations", typeof(ResEnumTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arduino.
        /// </summary>
        public static string EnumIotDevicePlattforms_Arduino {
            get {
                return ResourceManager.GetString("EnumIotDevicePlattforms_Arduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pc / Linux / Mac.
        /// </summary>
        public static string EnumIotDevicePlattforms_DotNet {
            get {
                return ResourceManager.GetString("EnumIotDevicePlattforms_DotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP32.
        /// </summary>
        public static string EnumIotDevicePlattforms_Esp32 {
            get {
                return ResourceManager.GetString("EnumIotDevicePlattforms_Esp32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opensense Sensor.
        /// </summary>
        public static string EnumIotDevicePlattforms_OpenSense {
            get {
                return ResourceManager.GetString("EnumIotDevicePlattforms_OpenSense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertiger Sensor.
        /// </summary>
        public static string EnumIotDevicePlattforms_Prebuilt {
            get {
                return ResourceManager.GetString("EnumIotDevicePlattforms_Prebuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspberry Pi.
        /// </summary>
        public static string EnumIotDevicePlattforms_RaspberryPi {
            get {
                return ResourceManager.GetString("EnumIotDevicePlattforms_RaspberryPi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über bluetooth low energy.
        /// </summary>
        public static string EnumIotDeviceUpstreamTypes_Ble {
            get {
                return ResourceManager.GetString("EnumIotDeviceUpstreamTypes_Ble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iot Gerät läuft im Gateway.
        /// </summary>
        public static string EnumIotDeviceUpstreamTypes_InGateway {
            get {
                return ResourceManager.GetString("EnumIotDeviceUpstreamTypes_InGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über OpenSense.
        /// </summary>
        public static string EnumIotDeviceUpstreamTypes_OpenSense {
            get {
                return ResourceManager.GetString("EnumIotDeviceUpstreamTypes_OpenSense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über serielle Schnittstelle.
        /// </summary>
        public static string EnumIotDeviceUpstreamTypes_Serial {
            get {
                return ResourceManager.GetString("EnumIotDeviceUpstreamTypes_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über Ethernet / TCP.
        /// </summary>
        public static string EnumIotDeviceUpstreamTypes_Tcp {
            get {
                return ResourceManager.GetString("EnumIotDeviceUpstreamTypes_Tcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über TTN - TheThingsNetwork.
        /// </summary>
        public static string EnumIotDeviceUpstreamTypes_Ttn {
            get {
                return ResourceManager.GetString("EnumIotDeviceUpstreamTypes_Ttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luftdruck.
        /// </summary>
        public static string EnumMeasurementType_AirPressure {
            get {
                return ResourceManager.GetString("EnumMeasurementType_AirPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feuchtigkeit.
        /// </summary>
        public static string EnumMeasurementType_Humidity {
            get {
                return ResourceManager.GetString("EnumMeasurementType_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lichtstärke.
        /// </summary>
        public static string EnumMeasurementType_LightIntensity {
            get {
                return ResourceManager.GetString("EnumMeasurementType_LightIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstige.
        /// </summary>
        public static string EnumMeasurementType_Other {
            get {
                return ResourceManager.GetString("EnumMeasurementType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatur.
        /// </summary>
        public static string EnumMeasurementType_Temperature {
            get {
                return ResourceManager.GetString("EnumMeasurementType_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string EnumMeasurementType_Wind {
            get {
                return ResourceManager.GetString("EnumMeasurementType_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschreitung.
        /// </summary>
        public static string EnumNotificationType_Exceed {
            get {
                return ResourceManager.GetString("EnumNotificationType_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausfall.
        /// </summary>
        public static string EnumNotificationType_Failure {
            get {
                return ResourceManager.GetString("EnumNotificationType_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung.
        /// </summary>
        public static string EnumNotificationType_MovingAverage {
            get {
                return ResourceManager.GetString("EnumNotificationType_MovingAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertung.
        /// </summary>
        public static string EnumNotificationType_Rating {
            get {
                return ResourceManager.GetString("EnumNotificationType_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterschreitung.
        /// </summary>
        public static string EnumNotificationType_Undercut {
            get {
                return ResourceManager.GetString("EnumNotificationType_Undercut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzter Tag.
        /// </summary>
        public static string EnumOpensenseDataTimeframe_Day {
            get {
                return ResourceManager.GetString("EnumOpensenseDataTimeframe_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letztes halbe Jahr.
        /// </summary>
        public static string EnumOpensenseDataTimeframe_HalfYear {
            get {
                return ResourceManager.GetString("EnumOpensenseDataTimeframe_HalfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letztes Monat.
        /// </summary>
        public static string EnumOpensenseDataTimeframe_Month {
            get {
                return ResourceManager.GetString("EnumOpensenseDataTimeframe_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte 2 Monate.
        /// </summary>
        public static string EnumOpensenseDataTimeframe_TwoMonths {
            get {
                return ResourceManager.GetString("EnumOpensenseDataTimeframe_TwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte 2 Wochen.
        /// </summary>
        public static string EnumOpensenseDataTimeframe_TwoWeeks {
            get {
                return ResourceManager.GetString("EnumOpensenseDataTimeframe_TwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte 2 Jahre.
        /// </summary>
        public static string EnumOpensenseDataTimeframe_TwoYears {
            get {
                return ResourceManager.GetString("EnumOpensenseDataTimeframe_TwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Woche.
        /// </summary>
        public static string EnumOpensenseDataTimeframe_Week {
            get {
                return ResourceManager.GetString("EnumOpensenseDataTimeframe_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letztes Jahr.
        /// </summary>
        public static string EnumOpensenseDataTimeframe_Year {
            get {
                return ResourceManager.GetString("EnumOpensenseDataTimeframe_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über Internet.
        /// </summary>
        public static string EnumPositionSource_Internet {
            get {
                return ResourceManager.GetString("EnumPositionSource_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über Mobilfunk.
        /// </summary>
        public static string EnumPositionSource_Lbs {
            get {
                return ResourceManager.GetString("EnumPositionSource_Lbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von GPS Modul.
        /// </summary>
        public static string EnumPositionSource_Modul {
            get {
                return ResourceManager.GetString("EnumPositionSource_Modul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betriebssystem/Manuelle Eingabe.
        /// </summary>
        public static string EnumPositionSource_Pc {
            get {
                return ResourceManager.GetString("EnumPositionSource_Pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ablauf nach n Sekunden (lt. Übertragungsinterval).
        /// </summary>
        public static string EnumTransmission_Elapsedtime {
            get {
                return ResourceManager.GetString("EnumTransmission_Elapsedtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofort nach Messung.
        /// </summary>
        public static string EnumTransmission_Instantly {
            get {
                return ResourceManager.GetString("EnumTransmission_Instantly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach n Messwerten (lt. Übertragungsinterval).
        /// </summary>
        public static string EnumTransmission_NumberOfMeasurements {
            get {
                return ResourceManager.GetString("EnumTransmission_NumberOfMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit / Boolean.
        /// </summary>
        public static string EnumValueType_Bit {
            get {
                return ResourceManager.GetString("EnumValueType_Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenarray - byte[].
        /// </summary>
        public static string EnumValueType_Data {
            get {
                return ResourceManager.GetString("EnumValueType_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild als Datenarray - byte[].
        /// </summary>
        public static string EnumValueType_Image {
            get {
                return ResourceManager.GetString("EnumValueType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahl - Double, Int, byte, ....
        /// </summary>
        public static string EnumValueType_Number {
            get {
                return ResourceManager.GetString("EnumValueType_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text - string.
        /// </summary>
        public static string EnumValueType_Text {
            get {
                return ResourceManager.GetString("EnumValueType_Text", resourceCulture);
            }
        }
    }
}
