//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewIncomeOutput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewIncomeOutput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewIncomeOutput", typeof(ResViewIncomeOutput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abos von Sensordaten.
        /// </summary>
        public static string HowToCollectIxiesItem1Key {
            get {
                return ResourceManager.GetString("HowToCollectIxiesItem1Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-5 IXie&apos;s pro Tag und Abo.
        /// </summary>
        public static string HowToCollectIxiesItem1Value {
            get {
                return ResourceManager.GetString("HowToCollectIxiesItem1Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor bewerten.
        /// </summary>
        public static string HowToCollectIxiesItem2Key {
            get {
                return ResourceManager.GetString("HowToCollectIxiesItem2Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 IXie&apos;s je Bewertung.
        /// </summary>
        public static string HowToCollectIxiesItem2Value {
            get {
                return ResourceManager.GetString("HowToCollectIxiesItem2Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übermitteln von Sensordaten.
        /// </summary>
        public static string HowToCollectIxiesItem3Key {
            get {
                return ResourceManager.GetString("HowToCollectIxiesItem3Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-3 IXie&apos;s pro Tag.
        /// </summary>
        public static string HowToCollectIxiesItem3Value {
            get {
                return ResourceManager.GetString("HowToCollectIxiesItem3Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verknüpfen eines Sensors (hat mindestens 1 Wert übermittelt).
        /// </summary>
        public static string HowToCollectIxiesItem4Key {
            get {
                return ResourceManager.GetString("HowToCollectIxiesItem4Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 IXie&apos;s einmalig.
        /// </summary>
        public static string HowToCollectIxiesItem4Value {
            get {
                return ResourceManager.GetString("HowToCollectIxiesItem4Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abos von Sensordaten.
        /// </summary>
        public static string HowToSpendIxiesItem1Key {
            get {
                return ResourceManager.GetString("HowToSpendIxiesItem1Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-6 IXie&apos;s pro Tag und Abo.
        /// </summary>
        public static string HowToSpendIxiesItem1Value {
            get {
                return ResourceManager.GetString("HowToSpendIxiesItem1Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkung.
        /// </summary>
        public static string LblColumnHeaderAnnotation {
            get {
                return ResourceManager.GetString("LblColumnHeaderAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guthaben.
        /// </summary>
        public static string LblColumnHeaderCredit {
            get {
                return ResourceManager.GetString("LblColumnHeaderCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitpunkt.
        /// </summary>
        public static string LblGridHeaderTimestamp {
            get {
                return ResourceManager.GetString("LblGridHeaderTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einnahmen/Ausgaben.
        /// </summary>
        public static string LblPageTitle {
            get {
                return ResourceManager.GetString("LblPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelles Guthaben.
        /// </summary>
        public static string TxtCurrentCredit {
            get {
                return ResourceManager.GetString("TxtCurrentCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie sammle ich IXie&apos;s.
        /// </summary>
        public static string TxtHowToCollectIxies {
            get {
                return ResourceManager.GetString("TxtHowToCollectIxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie kann ich meine IXie&apos;s ausgeben.
        /// </summary>
        public static string TxtHowToSpendIxies {
            get {
                return ResourceManager.GetString("TxtHowToSpendIxies", resourceCulture);
            }
        }
    }
}
