//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewInfo", typeof(ResViewInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Gateway Applikation.
        /// </summary>
        public static string CmdDownloadGateway {
            get {
                return ResourceManager.GetString("CmdDownloadGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Gateway Konfiguration.
        /// </summary>
        public static string CmdDownloadGatewayConfig {
            get {
                return ResourceManager.GetString("CmdDownloadGatewayConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download TCP Sensor Applikation.
        /// </summary>
        public static string CmdDownloadTcpApplication {
            get {
                return ResourceManager.GetString("CmdDownloadTcpApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Um die Kommunikation von Sensor und Server zu gewährleisten, muss Ihr
        ///Gateway während die Sensoren Daten versenden laufen.
        ///Hierfür laden Sie die Gateway-App und die dazu passende Gateway
        ///Konfiguration herunter.
        ///Anschließend entzippen Sie die GatewayApp.zip Datei und starten Sie die darin
        ///befindliche .exe Datei.
        ///Befolgen Sie nun den Aufforderungen in der Applikation und ihr Gateway ist
        ///Betriebsbereit.
        ///(Die GatewayApplikation speichert sich nach dem neustarten die Konfiguration,
        ///weshalb die Aufford [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbetriebnahme.
        /// </summary>
        public static string Installation {
            get {
                return ResourceManager.GetString("Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte Loggen Sie sich über den Menüpunkt &quot;Login&quot; ein oder erstellen Sie dort ein Benutzerkonto. Danach finden sie auf der Installationsseite Informationen wie Sie ihre Sensoren in Betrieb nehmen.
        /// </summary>
        public static string NotLoggedInText {
            get {
                return ResourceManager.GetString("NotLoggedInText", resourceCulture);
            }
        }
    }
}
