//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewMyRatings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewMyRatings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewMyRatings", typeof(ResViewMyRatings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messwert.
        /// </summary>
        public static string LblMeasurementValue {
            get {
                return ResourceManager.GetString("LblMeasurementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Bewertungen.
        /// </summary>
        public static string LblPageTitle {
            get {
                return ResourceManager.GetString("LblPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertung.
        /// </summary>
        public static string LblRating {
            get {
                return ResourceManager.GetString("LblRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertungen.
        /// </summary>
        public static string LblRatings {
            get {
                return ResourceManager.GetString("LblRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        public static string LblSensor {
            get {
                return ResourceManager.GetString("LblSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitpunkt.
        /// </summary>
        public static string LblTimeStamp {
            get {
                return ResourceManager.GetString("LblTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Bewertung wirklich löschen?.
        /// </summary>
        public static string MsgConfirmDelete {
            get {
                return ResourceManager.GetString("MsgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertung konnte nicht gelöscht werden.
        /// </summary>
        public static string MsgFailedToDeleteRating {
            get {
                return ResourceManager.GetString("MsgFailedToDeleteRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertung gelöscht.
        /// </summary>
        public static string MsgRatingDeleted {
            get {
                return ResourceManager.GetString("MsgRatingDeleted", resourceCulture);
            }
        }
    }
}
