//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewEditGlobalConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewEditGlobalConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewEditGlobalConfig", typeof(ResViewEditGlobalConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTN ApiKey.
        /// </summary>
        public static string LblTtnApiKey {
            get {
                return ResourceManager.GetString("LblTtnApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTN ApplicationID.
        /// </summary>
        public static string LblTtnApplicationId {
            get {
                return ResourceManager.GetString("LblTtnApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string LblTtnDescription {
            get {
                return ResourceManager.GetString("LblTtnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LblTtnName {
            get {
                return ResourceManager.GetString("LblTtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTN UserID.
        /// </summary>
        public static string LblTtnUserId {
            get {
                return ResourceManager.GetString("LblTtnUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTN Zone.
        /// </summary>
        public static string LblTtnZone {
            get {
                return ResourceManager.GetString("LblTtnZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTN Account.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der globale Api-Key des Users.
        /// </summary>
        public static string PlaceholderTtnApiKey {
            get {
                return ResourceManager.GetString("PlaceholderTtnApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die ApplikationID der erzeugten Applikation.
        /// </summary>
        public static string PlaceholderTtnAppId {
            get {
                return ResourceManager.GetString("PlaceholderTtnAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung der Konfiguration.
        /// </summary>
        public static string PlaceholderTtnDescription {
            get {
                return ResourceManager.GetString("PlaceholderTtnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name der Konfiguration.
        /// </summary>
        public static string PlaceholderTtnName {
            get {
                return ResourceManager.GetString("PlaceholderTtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Userid die bei der Registrierung angegeben wurde.
        /// </summary>
        public static string PlaceholderTtnUserId {
            get {
                return ResourceManager.GetString("PlaceholderTtnUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der TTN-Server. Zb. eu1.cloud.thethings.network.
        /// </summary>
        public static string PlaceholderTtnZone {
            get {
                return ResourceManager.GetString("PlaceholderTtnZone", resourceCulture);
            }
        }
    }
}
