//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewEditAbo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewEditAbo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewEditAbo", typeof(ResViewEditAbo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosten/Wert.
        /// </summary>
        public static string LblCostsValue {
            get {
                return ResourceManager.GetString("LblCostsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschreitung Wert.
        /// </summary>
        public static string LblExceedValue {
            get {
                return ResourceManager.GetString("LblExceedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausfall bei mehr als (Minuten).
        /// </summary>
        public static string LblFailureMinutes {
            get {
                return ResourceManager.GetString("LblFailureMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messwert Einstellungen.
        /// </summary>
        public static string LblMeasurementSettings {
            get {
                return ResourceManager.GetString("LblMeasurementSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benachrichtigungen.
        /// </summary>
        public static string LblMessages {
            get {
                return ResourceManager.GetString("LblMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benachrichtigungen für.
        /// </summary>
        public static string LblMessagesFor {
            get {
                return ResourceManager.GetString("LblMessagesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung vom Mittelwert.
        /// </summary>
        public static string LblMovingAverage {
            get {
                return ResourceManager.GetString("LblMovingAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abo verwalten.
        /// </summary>
        public static string LblPageTitle {
            get {
                return ResourceManager.GetString("LblPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertungen.
        /// </summary>
        public static string LblRatings {
            get {
                return ResourceManager.GetString("LblRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensoranbindung.
        /// </summary>
        public static string LblSensorConnection {
            get {
                return ResourceManager.GetString("LblSensorConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonniert.
        /// </summary>
        public static string LblSubscribed {
            get {
                return ResourceManager.GetString("LblSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        public static string LblType {
            get {
                return ResourceManager.GetString("LblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterschreitung Wert.
        /// </summary>
        public static string LblUndercutValue {
            get {
                return ResourceManager.GetString("LblUndercutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Sensoren verfügbar.
        /// </summary>
        public static string TxtNoSensorsAvailable {
            get {
                return ResourceManager.GetString("TxtNoSensorsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonnieren.
        /// </summary>
        public static string TxtSubscribe {
            get {
                return ResourceManager.GetString("TxtSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonnieren für.
        /// </summary>
        public static string TxtSubscribeFor {
            get {
                return ResourceManager.GetString("TxtSubscribeFor", resourceCulture);
            }
        }
    }
}
