//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewConfigs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewConfigs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewConfigs", typeof(ResViewConfigs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppEUI automatisch generieren.
        /// </summary>
        public static string LblAutoGenerateAppEui {
            get {
                return ResourceManager.GetString("LblAutoGenerateAppEui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppKey automatisch generieren.
        /// </summary>
        public static string LblAutoGenerateAppKey {
            get {
                return ResourceManager.GetString("LblAutoGenerateAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevEUI automatisch generieren.
        /// </summary>
        public static string LblAutoGenerateDevEui {
            get {
                return ResourceManager.GetString("LblAutoGenerateDevEui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device automatisch auf TTN anlegen.
        /// </summary>
        public static string LblCreateDevice {
            get {
                return ResourceManager.GetString("LblCreateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id des Iot Geräts.
        /// </summary>
        public static string LblIdOfIot {
            get {
                return ResourceManager.GetString("LblIdOfIot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lora Frequency-Plan.
        /// </summary>
        public static string LblLorawanFrequencyPlan {
            get {
                return ResourceManager.GetString("LblLorawanFrequencyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physikalische Lora Version.
        /// </summary>
        public static string LblLorawanPhysicalVersion {
            get {
                return ResourceManager.GetString("LblLorawanPhysicalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorawanversion.
        /// </summary>
        public static string LblLorawanVersion {
            get {
                return ResourceManager.GetString("LblLorawanVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTN Account.
        /// </summary>
        public static string LblTtnAccount {
            get {
                return ResourceManager.GetString("LblTtnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTN AppKey.
        /// </summary>
        public static string LblTtnAppKey {
            get {
                return ResourceManager.GetString("LblTtnAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ttn App/Join Eui.
        /// </summary>
        public static string LblTtnAppUI {
            get {
                return ResourceManager.GetString("LblTtnAppUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTN Beschreibung.
        /// </summary>
        public static string LblTtnDescription {
            get {
                return ResourceManager.GetString("LblTtnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ttn Dev Eui.
        /// </summary>
        public static string LblTtnDevEui {
            get {
                return ResourceManager.GetString("LblTtnDevEui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join über OTAA.
        /// </summary>
        public static string LblTtnSupportsJoin {
            get {
                return ResourceManager.GetString("LblTtnSupportsJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTN Konfiguration.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appkey des Geräts.
        /// </summary>
        public static string PlaceholderTtnAppKey {
            get {
                return ResourceManager.GetString("PlaceholderTtnAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_eui des Geräts.
        /// </summary>
        public static string PlaceholderTtnAppUI {
            get {
                return ResourceManager.GetString("PlaceholderTtnAppUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string PlaceholderTtnDescription {
            get {
                return ResourceManager.GetString("PlaceholderTtnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wird vom Device benötigt um zu verbinden.
        /// </summary>
        public static string PlaceholderTtnDevUI {
            get {
                return ResourceManager.GetString("PlaceholderTtnDevUI", resourceCulture);
            }
        }
    }
}
