//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewEditMeasurementDefinition {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewEditMeasurementDefinition() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewEditMeasurementDefinition", typeof(ResViewEditMeasurementDefinition).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusätzliche (dynamische) Daten.
        /// </summary>
        public static string LblAdditionalDynamicData {
            get {
                return ResourceManager.GetString("LblAdditionalDynamicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusätzliche Einstellungen.
        /// </summary>
        public static string LblAdditionalSettings {
            get {
                return ResourceManager.GetString("LblAdditionalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Typen.
        /// </summary>
        public static string LblAvailableTypes {
            get {
                return ResourceManager.GetString("LblAvailableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string LblDType {
            get {
                return ResourceManager.GetString("LblDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datentyp Sensor.
        /// </summary>
        public static string LblDataTypeSensor {
            get {
                return ResourceManager.GetString("LblDataTypeSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messwert wurde bewertet.
        /// </summary>
        public static string LblMeasurementRated {
            get {
                return ResourceManager.GetString("LblMeasurementRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgabewert des Messwerts.
        /// </summary>
        public static string LblMeasurementReturnType {
            get {
                return ResourceManager.GetString("LblMeasurementReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messwert wurde abonniert.
        /// </summary>
        public static string LblMeasurementSubscribed {
            get {
                return ResourceManager.GetString("LblMeasurementSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messwert wurde deabonniert.
        /// </summary>
        public static string LblMeasurementUnsubscribed {
            get {
                return ResourceManager.GetString("LblMeasurementUnsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte Anzahl.
        /// </summary>
        public static string LblNumberBytes {
            get {
                return ResourceManager.GetString("LblNumberBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zufällige Zahl.
        /// </summary>
        public static string LblRandomNumber {
            get {
                return ResourceManager.GetString("LblRandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum zufälliger Wert.
        /// </summary>
        public static string LblRandomValueMax {
            get {
                return ResourceManager.GetString("LblRandomValueMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum zufälliger Wert.
        /// </summary>
        public static string LblRandomValueMin {
            get {
                return ResourceManager.GetString("LblRandomValueMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriff f. Forschungsinstitute.
        /// </summary>
        public static string LblResearchInstituteAccessGranted {
            get {
                return ResourceManager.GetString("LblResearchInstituteAccessGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensoranbindung.
        /// </summary>
        public static string LblSensorConnection {
            get {
                return ResourceManager.GetString("LblSensorConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        public static string LblType {
            get {
                return ResourceManager.GetString("LblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messwert erstellen.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusätzliche Einstellungen.
        /// </summary>
        public static string PlaceholderAdditionalSettings {
            get {
                return ResourceManager.GetString("PlaceholderAdditionalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string PlaceholderDescription {
            get {
                return ResourceManager.GetString("PlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Messwerts.
        /// </summary>
        public static string PlaceholderName {
            get {
                return ResourceManager.GetString("PlaceholderName", resourceCulture);
            }
        }
    }
}
