// (C) 2024 FOTEC Forschungs- und Technologietransfer GmbH
// Das Forschungsunternehmen der Fachhochschule Wiener Neustadt
// 
// Kontakt biss@fotec.at / www.fotec.at
// 
// Erstversion vom 23.1.2024 10:38
// Entwickler      Mandl Matthias (MMa)
// Projekt         IXchange

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Exchange.Resources;
using Microsoft.AspNetCore.Components;

namespace BlazorApp.Pages
{
    public partial class ViewConfigs
    {
        private readonly Dictionary<string, RenderFragment> dictionary = new Dictionary<string, RenderFragment>();

        /// <inheritdoc />
        protected override Task OnInitializedAsync()
        {
            dictionary.Add($"{ResViewConfigs.LblTtnAccount}:", TtnAccountRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblIdOfIot}:", TtnIotDeviceIdRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblTtnDescription}:", TtnDescriptionRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblAutoGenerateDevEui}:", TtnGenerateDevEuiRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblTtnDevEui}:", TtnDevEuiRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblAutoGenerateAppEui}:", TtnGenerateAppEuiRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblTtnAppUI}:", TtnAppEuiRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblAutoGenerateAppKey}:", TtnGenerateAppKeyRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblTtnAppKey}:", TtnAppKeyRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblTtnSupportsJoin}:", TtnSupportsJoinRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblCreateDevice}:", TtnCreateDeviceRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblLorawanVersion}:", TtnLorawanVersionRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblLorawanPhysicalVersion}:", TtnLorawanPhysicalVersionRenderFragment);
            dictionary.Add($"{ResViewConfigs.LblLorawanFrequencyPlan}:", TtnLorawanFrequencyPlanIdRenderFragment);

            return base.OnInitializedAsync();
        }
    }
}